steps:
  - name: 'gcr.io/cloud-builders/pnpm'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "BESOCCER_API_KEY=$_BESOCCER_API_KEY" > .env.production
        pnpm install
        pnpm build
        pnpm start

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
